name: build
on: [push, pull_request]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    name: ${{ matrix.config.image }}:${{ matrix.config.tag }}
    container:
      image: ${{ matrix.config.image }}:${{ matrix.config.tag }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {image: 'fedora', tag: 'latest'}
        - {image: 'debian', tag: 'latest'}
        - {image: 'ubuntu', tag: 'latest'}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Fedora)
      if: ${{ matrix.config.image == 'fedora' }}
      run: |
        dnf install -y R-core devscripts-checkbashisms python3-dnf

    - name: Install dependencies (Debian, Ubuntu)
      if: ${{ matrix.config.image != 'fedora' }}
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update && apt install -y r-base-core devscripts python3-apt

    - name: Check
      env:
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
      run: |
        export LANG=$(locale -a | grep utf8 | head -n1)
        Rscript -e 'install.packages("tinytest", repos="https://cran.r-project.org")'
        R CMD build . && mkdir check
        R CMD check bspm_*.tar.gz --no-manual -o check

    - name: Upload check results
      if: ${{ failure() }}
      uses: actions/upload-artifact@master
      with:
        name: r-${{ matrix.config.image }}-${{ matrix.config.tag }}-results
        path: check
